
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.7.0
 * Query Engine version: 3cff47a7f5d65c3ea74883f1d736e41d68ce91ed
 */
Prisma.prismaVersion = {
  client: "6.7.0",
  engine: "3cff47a7f5d65c3ea74883f1d736e41d68ce91ed"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  password: 'password',
  create_at: 'create_at',
  updated_at: 'updated_at',
  cliente_id: 'cliente_id',
  setor_id: 'setor_id',
  instituicao_id: 'instituicao_id'
};

exports.Prisma.ClienteScalarFieldEnum = {
  id: 'id',
  name: 'name',
  create_at: 'create_at',
  updated_at: 'updated_at'
};

exports.Prisma.SetorScalarFieldEnum = {
  id: 'id',
  name: 'name',
  create_at: 'create_at',
  updated_at: 'updated_at'
};

exports.Prisma.InstituicaoUnidadeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  create_at: 'create_at',
  updated_at: 'updated_at'
};

exports.Prisma.StatusOrdemdeServicoScalarFieldEnum = {
  id: 'id',
  name: 'name',
  create_at: 'create_at',
  updated_at: 'updated_at'
};

exports.Prisma.TipodeSolicitacaoScalarFieldEnum = {
  id: 'id',
  name: 'name',
  create_at: 'create_at',
  updated_at: 'updated_at'
};

exports.Prisma.TecnicoScalarFieldEnum = {
  id: 'id',
  name: 'name',
  create_at: 'create_at',
  updated_at: 'updated_at'
};

exports.Prisma.OrdemdeServicoScalarFieldEnum = {
  id: 'id',
  name: 'name',
  problemaOuSolicitacao: 'problemaOuSolicitacao',
  created_at: 'created_at',
  update_at: 'update_at',
  cliente_id: 'cliente_id',
  tecnico_id: 'tecnico_id',
  statusOrdemdeServico_id: 'statusOrdemdeServico_id',
  tipodesolicitacao_id: 'tipodesolicitacao_id',
  instituicaoUnidade_id: 'instituicaoUnidade_id'
};

exports.Prisma.FormTecnicoScalarFieldEnum = {
  id: 'id',
  name: 'name',
  diagnostico: 'diagnostico',
  solucao: 'solucao',
  assinatura: 'assinatura',
  status_id: 'status_id',
  statusOrdemdeServico_id: 'statusOrdemdeServico_id',
  ordemDeServico_id: 'ordemDeServico_id',
  created_at: 'created_at',
  update_at: 'update_at'
};

exports.Prisma.EquipamentoScalarFieldEnum = {
  id: 'id',
  name: 'name',
  patrimonio: 'patrimonio',
  create_at: 'create_at',
  updated_at: 'updated_at'
};

exports.Prisma.ControleDeAssistenciaTecnicaScalarFieldEnum = {
  id: 'id',
  name: 'name',
  mesAno: 'mesAno',
  idChamado: 'idChamado',
  assistencia: 'assistencia',
  observacoes: 'observacoes',
  osDaAssistencia: 'osDaAssistencia',
  dataDeRetirada: 'dataDeRetirada',
  equipamento_id: 'equipamento_id',
  statusReparo_id: 'statusReparo_id',
  statusTeste_id: 'statusTeste_id',
  instituicaoUnidade_id: 'instituicaoUnidade_id',
  tecnico_id: 'tecnico_id',
  cliente_id: 'cliente_id',
  create_at: 'create_at',
  updated_at: 'updated_at'
};

exports.Prisma.StatusReparoScalarFieldEnum = {
  id: 'id',
  name: 'name',
  create_at: 'create_at',
  updated_at: 'updated_at'
};

exports.Prisma.StatusTesteScalarFieldEnum = {
  id: 'id',
  name: 'name',
  create_at: 'create_at',
  updated_at: 'updated_at'
};

exports.Prisma.ControleDeLaudoTecnicoScalarFieldEnum = {
  id: 'id',
  descricaodoProblema: 'descricaodoProblema',
  mesAno: 'mesAno',
  osLab: 'osLab',
  instituicaoUnidade_id: 'instituicaoUnidade_id',
  equipamento_id: 'equipamento_id',
  tecnico_id: 'tecnico_id',
  create_at: 'create_at',
  updated_at: 'updated_at'
};

exports.Prisma.ControleDeLaboratioScalarFieldEnum = {
  id: 'id',
  nomedoEquipamento: 'nomedoEquipamento',
  marca: 'marca',
  defeito: 'defeito',
  osDeAbertura: 'osDeAbertura',
  osDeDevolucao: 'osDeDevolucao',
  data_de_Chegada: 'data_de_Chegada',
  data_de_Finalizacao: 'data_de_Finalizacao',
  statusControledeLaboratorio_id: 'statusControledeLaboratorio_id',
  instituicao_id: 'instituicao_id',
  cliente_id: 'cliente_id',
  equipamento_id: 'equipamento_id'
};

exports.Prisma.StatusControledeLaboratorioScalarFieldEnum = {
  id: 'id',
  name: 'name',
  create_at: 'create_at',
  updated_at: 'updated_at'
};

exports.Prisma.ControleDeMaquinasPendentesLaboratorioScalarFieldEnum = {
  id: 'id',
  numeroDeSerie: 'numeroDeSerie',
  ssd: 'ssd',
  idDaOs: 'idDaOs',
  obs: 'obs',
  create_at: 'create_at',
  updated_at: 'updated_at',
  equipamento_id: 'equipamento_id',
  statusMaquinasPendentesLab_id: 'statusMaquinasPendentesLab_id'
};

exports.Prisma.StatusMaquinasPendentesLabScalarFieldEnum = {
  id: 'id',
  name: 'name',
  create_at: 'create_at',
  updated_at: 'updated_at'
};

exports.Prisma.ControledeMaquinasPendentesOroScalarFieldEnum = {
  id: 'id',
  datadaInstalacao: 'datadaInstalacao',
  osInstalacao: 'osInstalacao',
  osRetirada: 'osRetirada',
  create_at: 'create_at',
  updated_at: 'updated_at',
  equipamento_id: 'equipamento_id',
  instituicaoUnidade_id: 'instituicaoUnidade_id',
  statusMaquinasPendentesOro_id: 'statusMaquinasPendentesOro_id'
};

exports.Prisma.StatusMaquinasPendentesOroScalarFieldEnum = {
  id: 'id',
  name: 'name',
  create_at: 'create_at',
  updated_at: 'updated_at'
};

exports.Prisma.DocumentacaoTecnicaScalarFieldEnum = {
  id: 'id',
  titulo: 'titulo',
  descricao: 'descricao',
  create_at: 'create_at',
  updated_at: 'updated_at',
  cliente_id: 'cliente_id',
  tecnico_id: 'tecnico_id',
  instituicao_id: 'instituicao_id'
};

exports.Prisma.SolicitacaoDeComprasScalarFieldEnum = {
  id: 'id',
  itemSolicitado: 'itemSolicitado',
  solicitante: 'solicitante',
  motivoDaSolicitacao: 'motivoDaSolicitacao',
  preco: 'preco',
  linkDeCompra: 'linkDeCompra',
  create_at: 'create_at',
  updated_at: 'updated_at',
  statusCompras_id: 'statusCompras_id'
};

exports.Prisma.StatusComprasScalarFieldEnum = {
  id: 'id',
  name: 'name',
  create_at: 'create_at',
  updated_at: 'updated_at'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  User: 'User',
  Cliente: 'Cliente',
  Setor: 'Setor',
  InstituicaoUnidade: 'InstituicaoUnidade',
  statusOrdemdeServico: 'statusOrdemdeServico',
  TipodeSolicitacao: 'TipodeSolicitacao',
  Tecnico: 'Tecnico',
  OrdemdeServico: 'OrdemdeServico',
  FormTecnico: 'FormTecnico',
  Equipamento: 'Equipamento',
  controleDeAssistenciaTecnica: 'controleDeAssistenciaTecnica',
  statusReparo: 'statusReparo',
  StatusTeste: 'StatusTeste',
  controleDeLaudoTecnico: 'controleDeLaudoTecnico',
  controleDeLaboratio: 'controleDeLaboratio',
  statusControledeLaboratorio: 'statusControledeLaboratorio',
  controleDeMaquinasPendentesLaboratorio: 'controleDeMaquinasPendentesLaboratorio',
  statusMaquinasPendentesLab: 'statusMaquinasPendentesLab',
  controledeMaquinasPendentesOro: 'controledeMaquinasPendentesOro',
  statusMaquinasPendentesOro: 'statusMaquinasPendentesOro',
  documentacaoTecnica: 'documentacaoTecnica',
  solicitacaoDeCompras: 'solicitacaoDeCompras',
  statusCompras: 'statusCompras'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
